name: Deploy to Clojars

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  deploy_to_clojars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: '2.8.1'
      - uses: actions/checkout@v2

      - name: Deploy to clojars
#        run: lein deploy clojars
        run: ls -l
        env:
            CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
            CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
